version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"